import json
import socket
import threading
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from dotenv import load_dotenv
from gui_server import ServerGUI
import tkinter as tk
from logger import log_connection_event, log_transaction_event
# Cryptography dependencies
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
import secrets

from shared.crypto_utils import (
    encrypt_with_AES_key,
    decrypt_with_AES_key,
    generate_master_secret_from_pms,
    generate_enc_and_MAC_key,
    secure_send,
    secure_receive,
)


# use the db_lock to read/write to/from users.json file to allow for synchronization
USER_FILE = os.path.join(os.path.dirname(__file__), "users.json")

USER_FILE = os.path.abspath(USER_FILE)

db_lock = threading.Lock()

MAX_ATMS = 3
active_atms = set()
atm_lock = threading.Lock()

server_nonces = {}
server_nonces_lock = threading.Lock()
nonce_ceiling = 10000000

iter = 10000

def load_users():
    if os.path.exists(USER_FILE):
        with open(USER_FILE, "r") as f:
            return json.load(f)
    return {}

def save_users(users):
    print("[DEBUG] Saving users to file...")
    with open(USER_FILE, "w") as f:
        json.dump(users, f)
    print("[DEBUG] Save complete.")

# API to generate shared symmetric key for an ATM and the server, the one we assume
# both "already have", referred to as K_s in sys design diagram
def generate_server_ATM_shared_key(atm_number: int):
    shared_secret = os.getenv("ATM_SERVER_SHARED_SECRET")
    shared_secret_bytes = shared_secret.encode()
    salt_str = os.getenv(f"ATM_{atm_number}_SALT")
    salt_bytes = salt_str.encode()
    # derive key
    kdf = PBKDF2HMAC(
        algorithm = hashes.SHA256(),
        length = 32,
        salt = salt_bytes,
        iterations = iter,
    )

    return kdf.derive(shared_secret_bytes)

# generate and append a random int to server_nonces (thread safe)
def generate_nonce():
    # thread safe lock
    with server_nonces_lock:
        rand_int = secrets.randbelow(nonce_ceiling)
        # generate nonce repetitively until we get a unique value not in our server nonces
        while(True):
            if rand_int not in server_nonces.keys():
                break
            rand_int = secrets.randbelow(nonce_ceiling)
        server_nonces[rand_int] = False
        return rand_int
    
def append_server_nonce(nonce: int):
    with server_nonces_lock:
        if server_nonces[nonce]:
            print("that nonce has already been used!")
        else:
            server_nonces[nonce] = True

# customer sends N_atm (nonce generated by ATM), we decrypt it and send unencrypted value back in next message
""" args: 
customer_nonce_encrypted: The encrypted nonce value the ATM generated and sent to server
symmetric_AES_key: K_s 
ATM_IV: initialization vector (should be generated by ATM) used to decrypt nonce
"""
def authenticate_customer(customer_nonce_encrypted: bytes, symmetric_AES_key: bytes, ATM_IV: bytes):
    print()

# authentication protocol that generates the shared encryption key and MAC key
def authentication_protocol():
    print("temp")

def get_balance(username):
    with db_lock:
        return USER_DATABASE[username]["balance"]

def update_balance(username, new_balance):
    with db_lock:
        USER_DATABASE[username]["balance"] = new_balance
        save_users(USER_DATABASE)

USER_DATABASE = load_users()

HOST = 'localhost'
PORT = 8888

def allocate_atm_number():
    with atm_lock:
        for i in range(1, MAX_ATMS + 1):
            if i not in active_atms:
                active_atms.add(i)  # Reserve ATM here atomically
                print(f"[SERVER DEBUG] Allocated ATM number: {i}")
                print(f"[SERVER DEBUG] Active ATMs: {active_atms}")
                return i
        return None

def release_atm_number(atm_number):
    with atm_lock:
        active_atms.discard(atm_number)

# prerequisites to handling a client:
# generate shared symmetric AES key
def handle_client(conn: socket.socket, addr, connection_log: list, transaction_log: list, atm_number: int):
    print(f"[+] Connection from {addr}")
    authenticated = False
    K_s = None
    init_vector = None
    encryption_key = None
    MAC_key = None
    username = None
    local_username = None
    server_nonce = None
    client_nonce = None
    if atm_number is None:
        print("[!] Maximum number of ATM connections reached.")
        conn.sendall("ATM_LIMIT_REACHED".encode())
        conn.close()
        return

    conn.sendall(json.dumps({"atm_number": atm_number}).encode())
    try:
        while True:
            data = conn.recv(1024).decode()
            if not data:
                break
            message = json.loads(data)
            print(f"message:{message}")
            if K_s is None:
                K_s = generate_server_ATM_shared_key(int(message["atm_number"]))
                atm_number = int(message["atm_number"])
                init_vector = bytes.fromhex(message["iv"])
            # if they're not authenticated and they aren't attempting to login or signup
            if not authenticated:
                USER_DATABASE = load_users()
                if message["type"] != "auth":
                    print("must authenticate before proceeding")
                    conn.sendall("AUTH failed".encode())
                    break

                step = message.get("step")

                if step == 0:  # Registration step
                    K_s = generate_server_ATM_shared_key(atm_number)
                    iv = bytes.fromhex(message["iv"])
                    ciphertext = bytes.fromhex(message["encr_payload"])
                    decrypted = decrypt_with_AES_key(ciphertext, K_s, iv)
                    register_data = json.loads(decrypted)

                    username = register_data.get("username")
                    password = register_data.get("password")

                    print(f"[SERVER DEBUG] userdatabase: {USER_DATABASE}")
                    if not username or not password:
                        conn.sendall(json.dumps({"status": "FAIL", "message": "Missing credentials"}).encode())
                        break

                    if username in USER_DATABASE:
                        conn.sendall(json.dumps({"status": "FAIL", "message": "Username already exists"}).encode())
                        break

                    with db_lock:
                        USER_DATABASE[username] = {"password": password, "balance": 0}
                        save_users(USER_DATABASE)

                    conn.sendall(json.dumps({"status": "SUCCESS", "message": "Registered successfully"}).encode())
                    break
                elif step == 1:
                    print("[SERVER DEBUG] Received auth step 1")
                    K_s = generate_server_ATM_shared_key(atm_number)
                    init_vector = bytes.fromhex(message["iv"])
                    cipher_bytes = bytes.fromhex(message["encr_payload"])
                    decrypted = decrypt_with_AES_key(cipher_bytes, K_s, init_vector)
                    auth_payload_recv = json.loads(decrypted)
                    client_nonce = int(auth_payload_recv["N_atm"])

                    # Save server_nonce for later validation
                    server_nonce = generate_nonce()

                    response_data = {
                        "N_s": server_nonce,
                        "N_atm": client_nonce
                    }

                    iv2 = secrets.token_bytes(16)
                    encrypted_response = encrypt_with_AES_key(json.dumps(response_data), K_s, iv2)
                    print("[SERVER DEBUG] Encrypted response:", encrypted_response.hex())
                    response_msg = {
                        "type": "auth",
                        "step": 2,
                        "iv": iv2.hex(),
                        "encr_payload": encrypted_response.hex()
                    }
                    print("[SERVER DEBUG] Sending challenge response:", response_msg)
                    try:
                        conn.sendall(json.dumps(response_msg).encode())
                    except Exception as e:
                        print(f"[!] Error sending response to client {addr}: {e}")
                        break

                elif step == 3:
                    iv = bytes.fromhex(message["iv"])
                    ciphertext = bytes.fromhex(message["payload"])
                    decrypted = decrypt_with_AES_key(ciphertext, K_s, iv)
                    auth_payload_recv = json.loads(decrypted)

                    if int(auth_payload_recv["N_s"]) != server_nonce:
                        conn.sendall("AUTH failed".encode())
                        break
                    print("[SERVER DEBUG] Sending success message:", response_msg)

                    conn.sendall(json.dumps({"type": "auth", "status": "success"}).encode())

                elif step == 5:
                    iv = bytes.fromhex(message["iv"])
                    ciphertext = bytes.fromhex(message["payload"])
                    decrypted = decrypt_with_AES_key(ciphertext, K_s, iv)
                    auth_payload_recv = json.loads(decrypted)
                    print("[SERVER DEBUG] Received PMS payload:", auth_payload_recv)
                    local_username = auth_payload_recv.get("username")
                    password = auth_payload_recv.get("password")
                    if local_username and password:
                        if local_username in USER_DATABASE and USER_DATABASE[local_username]["password"] == password:
                            print("[SERVER DEBUG] Authentication successful")
                            log_connection_event(connection_log, local_username, "login", addr[1])
                            pre_master_secret = auth_payload_recv["pms"]
                            master_secret = generate_master_secret_from_pms(pre_master_secret, atm_number, client_nonce, server_nonce)
                            encryption_key, MAC_key = generate_enc_and_MAC_key(master_secret, pre_master_secret.encode())
                            authenticated = True
                            response = {"type": "auth", "status": "success", "message": "Login successful"}
                            conn.sendall(json.dumps(response).encode())
                        else:
                            response = {"type": "auth", "status": "FAIL", "message": "Invalid credentials"}
                            conn.sendall(json.dumps(response).encode())
                            return
                    else:
                        response = {"type": "auth", "status": "FAIL", "message": "Missing credentials"}
                        conn.sendall(json.dumps(response).encode())
                continue

            secure_msg = secure_receive(message, encryption_key, MAC_key)
            print("[SERVER DEBUG] Received secure message:", secure_msg)

            if secure_msg["type"] == "transaction":
                username = secure_msg["username"].strip()
                action = secure_msg["action"].strip()
                amount = secure_msg.get("amount", 0)
                print(f"[>] Transaction request: {username} - Action: {action} - Amount: {amount}")

                if username not in USER_DATABASE:
                    print(f"[SERVER DEBUG] User {username} not found")
                    response = {"status": "FAIL", "message": "User not found"}
                    conn.sendall(json.dumps(response).encode())
                    continue

                if action == "deposit":
                    balance = get_balance(username)
                    new_balance = balance + amount
                    update_balance(username, new_balance)
                    response = {"status": "SUCCESS", "balance": new_balance}
                    log_transaction_event(transaction_log, username, "deposit", amount)
                elif action == "withdraw":
                    balance = get_balance(username)
                    if amount > balance:
                        response = {"status": "FAIL", "message": "Insufficient funds"}
                    else:
                        new_balance = balance - amount
                        update_balance(username, new_balance)
                        response = {"status": "SUCCESS", "balance": new_balance}
                        log_transaction_event(transaction_log, username, "withdraw", amount)
                elif action == "balance_inquiry":
                    balance = get_balance(username)
                    response = {"status": "SUCCESS", "balance": balance}
                    log_transaction_event(transaction_log, username, "balance_inquiry")
                
                secure_payload = secure_send(response, encryption_key, MAC_key)
                print("[SERVER DEBUG] Sending secure response:", secure_payload)
                conn.sendall(json.dumps(secure_payload).encode())
            else:
                conn.sendall("UNKNOWN_COMMAND".encode())
    except Exception as e:
        print(f"[!] Error handling client {addr}: {e}")
    finally:
        conn.close()
        if local_username:
            log_connection_event(connection_log, local_username, "logout", addr[1])
        if atm_number:
            release_atm_number(atm_number)
        print(f"[-] Disconnected: {addr}")

if __name__ == "__main__":
    connection_log = []
    transaction_log = []
    load_dotenv()

    def assign_and_handle(conn, addr, connection_log, transaction_log):
        atm_number = allocate_atm_number()
        if atm_number is None:
            print("[!] Max ATM limit reached.")
            conn.sendall("ATM_LIMIT_REACHED".encode())
            conn.close()
            return

        # Pass atm_number into the handler
        handle_client(conn, addr, connection_log, transaction_log, atm_number)

    def start_server():
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server_socket:
            server_socket.bind((HOST, PORT))
            server_socket.listen()
            print(f"[+] Server listening on {HOST}:{PORT}")

            while True:
                conn, addr = server_socket.accept()
                thread = threading.Thread(
                    target=assign_and_handle,
                    args=(conn, addr, connection_log, transaction_log)
                )
                thread.start()

    # Start server thread
    threading.Thread(target=start_server, daemon=True).start()

    # Start GUI
    root = tk.Tk()
    gui = ServerGUI(root, connection_log, transaction_log)
    root.mainloop()


